version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "
      while ! nc -z db 5432; do
        echo 'Waiting for Postgres...';
        sleep 1;
      done;
      alembic upgrade head && poetry run python app.py"
    ports:
      - "8000:8000"

volumes:
  postgres_data: